version: "3.8"
services:
  alarm-db:
    image: postgres
    ports:
        - 5432:5432
    networks: 
      - alarm-network
    restart: always
    volumes:
      - 'E:\Alarm\DB:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: alarm
      POSTGRES_USER: alarm
      POSTGRES_PASSWORD: sqlitesucktmyb0llzzz
  alarm: 
    networks: 
      - alarm-network
    ports:
      - "443:3000"
    volumes:
      - 'E:\Alarm\config\:/config/'
      - 'E:\Alarm\migration\:/migration/'
    image: alaaarm:latest
    restart: always
    container_name: alarm-container
    depends_on: 
      - alarm-db
networks: 
  alarm-network:
    name: alarm-network
    